# Chapter 6 - Other Popular Machine Learning Methods
## Segment 2 - A neural network with a Perceptron

In [2]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [3]:
from sklearn.linear_model import Perceptron

In [5]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [7]:
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

In [8]:
standardized_X_test[0:10,]

array([[-0.38631141,  1.18597176, -1.41881615, -1.27958918],
       [-1.23431207,  0.1837421 , -1.29737682, -1.41867496],
       [-0.38631141, -1.5701598 ,  0.03845579, -0.16690294],
       [-1.51697895,  0.43429952, -1.23665715, -1.27958918],
       [ 0.46168925, -0.06681531,  0.58493276,  0.38944018],
       [-1.23431207, -1.5701598 , -0.20442287, -0.16690294],
       [ 0.46168925, -0.56793014,  0.22061478,  0.2503544 ],
       [-1.94097928,  0.43429952, -1.41881615, -1.27958918],
       [ 0.03768892, -0.56793014,  0.88853108,  1.78029799],
       [ 1.59235679,  0.1837421 ,  0.76709175,  0.52852596]])

In [13]:
y_train

array([1, 0, 2, 2, 0, 0, 1, 1, 1, 1, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2, 1, 1,
       0, 1, 2, 0, 0, 1, 2, 0, 2, 1, 2, 1, 1, 0, 2, 1, 0, 2, 2, 2, 0, 2,
       2, 2, 1, 2, 0, 2, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 0, 2, 1, 2, 2, 1,
       1, 2, 0, 2, 0, 1, 0, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1, 0, 2, 0, 2, 0,
       2, 2, 0, 2, 2, 0, 0, 1, 1, 2, 2, 2, 0, 1, 0, 1, 2, 0, 1, 2, 2, 0,
       0, 1, 1, 1, 2, 0, 0, 1, 0, 0])

In [12]:
y_train.ravel()

array([1, 0, 2, 2, 0, 0, 1, 1, 1, 1, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2, 1, 1,
       0, 1, 2, 0, 0, 1, 2, 0, 2, 1, 2, 1, 1, 0, 2, 1, 0, 2, 2, 2, 0, 2,
       2, 2, 1, 2, 0, 2, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 0, 2, 1, 2, 2, 1,
       1, 2, 0, 2, 0, 1, 0, 2, 1, 0, 0, 2, 0, 0, 1, 1, 1, 0, 2, 0, 2, 0,
       2, 2, 0, 2, 2, 0, 0, 1, 1, 2, 2, 2, 0, 1, 0, 1, 2, 0, 1, 2, 2, 0,
       0, 1, 1, 1, 2, 0, 0, 1, 0, 0])

In [11]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3)
perceptron.fit(standardized_X_train, y_train)

Perceptron(eta0=0.15, max_iter=50)

In [14]:
y_pred = perceptron.predict(standardized_X_test)

In [15]:
print(y_test)

[0 0 1 0 1 1 1 0 2 1 2 2 0 1 0 2 1 1 0 1 0 2 2 2 0 0 1 1 1 2]


In [16]:
print(y_pred)

[0 0 1 0 2 1 2 0 2 2 2 2 0 2 0 2 2 2 0 2 0 2 2 2 0 0 1 2 2 2]


In [17]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.25      0.40        12
           2       0.47      1.00      0.64         8

    accuracy                           0.70        30
   macro avg       0.82      0.75      0.68        30
weighted avg       0.86      0.70      0.66        30



In [38]:
perceptron = Perceptron(max_iter=50, eta0=0.01, tol=1e-3)
perceptron.fit(standardized_X_train, y_train)
y_pred = perceptron.predict(standardized_X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.92      0.92      0.92        12
           2       0.88      0.88      0.88         8

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

